language: node_js
node_js:
- "6.1"
before_install:
- "npm install -g yarn"
cache:
  directories:
  - "$HOME/.yarn-cache"
install:
- "yarn"
- "npm run build"
before_deploy:
- "mkdir dep"
- "mkdir dep/no-cache"
- "mkdir dep/cache"
- "mv dist/index.html dep/no-cache/"
- "mv dist/* dep/cache/"
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: com-oauth2cloud-prod
    local-dir: dep/no-cache
    acl: public_read
    detect_encoding: true
    cache_control: max-age=0
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: com-oauth2cloud-prod
    local-dir: dep/cache
    acl: public_read
    detect_encoding: true
    cache_control: max-age=86400
    skip_cleanup: true
    on:
      tags: true
