language: node_js
node_js:
  - "6.1"

before_install:
  # Repo for newer Node.js versions
#  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.yarn-cache

install:
  - yarn
  - npm run build

deploy:
  provider: s3
  access_key_id: AKIAIBT4BO2VCSN4S3CQ
  secret_access_key:
    secure: OKtp7+jMYfNsSn5Ep5wDFPvvZlyXbvy5ppnZfijRXYtNSt0sbnAG1ZYUSJx0bvwFkUNLXSORl0tglFSZ5LtRIWm2XofeQVKqDq7DRbqcSj02l/vUSBIJVHBO7B6RPImcRatlfT6gjBSZVwbz3/q9qYLkT9C8zRXp/vQ/3rnfKd47/1N0z3pDjpSJ0OotYZd3NGoF6sr51fbsbnNzeNK4MKYUVKbOzSZ6wYt1VuR6f9IY29FhwlqWBlnlfBZigp3IK6wrAX2lvRq7PY/ik6oW6304RPPJrRTCs5yOGNe6SclzrPal+KucF7mCEWNIzQqYfkY+QCxXMpGXGdiK5GbSdyOZOyqOPP2+EfSRUf/jIXvCmeGOH/XXv8Ol1R5N62J7pxh90qtuhWdg5fkLE+sU8RjlgwV9WLiSR4NFDGuCETlUp7MB3JsSyTNxsabXmDgiGXYg+WclL5U+qkTlauRs7taVyoBiOSdGRxHOo7D8+V+RZxuLNc0gumrJFiUdatJOcZijHNvL7+JYwdIvKDJsiE00ZvbCit2tUjs7NgRc+nH+5h3W2uc6DpzUExHC/fbH1d4/sQedyhNIydtgCKcWOprBy4tcPyfwC77KJ+vD/TYv+6lium9TkaXELmC1Kd9nqFuM/1e4rAiIyv/wt1IknVQqZBBFYCMqkywX9fdhxNU=
  bucket: com-oauth2cloud-prod
  local-dir: dist
  acl: public_read
  detect_encoding: true # <== default is false
  cache_control: "max-age=0"
  on:
    tags: true
